name = "skycars-official"
main = "src/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist"

[build]
command = "npm run build"
upload.format = "service-worker"

[env.production]
name = "skycars-prod"
route = "your-domain.com/*"
zone_id = "your_zone_id"

[vars]
MONGODB_URI = "mongodb+srv://skycars-admin:mrVDdv9lAVnTbNrV@skycars.1ceyw.mongodb.net/?retryWrites=true&w=majority&appName=SkyCars"
JWT_SECRET = "skycars-secret-key-2024"

[[d1_databases]]
binding = "DB"  # This is how you'll access it in your code
database_name = "skycars"
database_id = "80462549-3646-480d-accc-977ee12c3876"  # Copy this from the create command output