name = "skycars"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[build]
command = "npm run build"
upload.format = "service-worker"

[env.production]
name = "skycars-prod"
route = "your-domain.com/*"
zone_id = "your_zone_id"

[vars]
MONGODB_URI = "mongodb+srv://skycars-admin:mrVDdv9lAVnTbNrV@skycars.1ceyw.mongodb.net/?retryWrites=true&w=majority&appName=SkyCars"
JWT_SECRET = "skycars-secret-key-2024"